# Generated by Django 3.2.5 on 2021-07-28 17:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='looking_for',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('FE', 'Front-End Developer'), ('FS', 'Full-Stack Developer'), ('BE', 'Back-End Developer'), ('GD', 'Graphic Designer')], max_length=2, verbose_name='looking for those roles'), blank=True, null=True, size=None),
        ),
    ]
