# Generated by Django 3.2.5 on 2021-08-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='joined',
            field=models.BooleanField(default=False, verbose_name='user joined?'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='nick',
            field=models.CharField(default='ft', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, choices=[('FE', 'Front-End Developer'), ('FS', 'Full-Stack Developer'), ('BE', 'Back-End Developer'), ('GD', 'Graphic Designer')], max_length=2),
        ),
    ]
