# Generated by Django 3.2.5 on 2021-08-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210824_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='nick',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('FE', 'Front-End Developer'), ('FS', 'Full-Stack Developer'), ('BE', 'Back-End Developer'), ('GD', 'Graphic Designer')], max_length=2, null=True),
        ),
    ]
