# Generated by Django 3.2.5 on 2021-07-28 17:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_announcement_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='what needs to be done'),
        ),
    ]
