# Generated by Django 3.2.5 on 2021-07-29 10:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_announcement_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='our_stack',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PY', 'python'), ('NJS', 'node.js'), ('PHP', 'php'), ('ROR', 'ruby on rails'), ('JSP', 'java'), ('ASX', '.net'), ('GO', 'golang'), ('HC', 'html&css'), ('JS', 'javascript'), ('TS', 'typescript'), ('JSX', 'react'), ('ANG', 'angular'), ('VUE', 'vue.js'), ('CPP', 'c++'), ('C', 'c'), ('RN', 'react native'), ('FL', 'flutter'), ('SC', 'scala'), ('EX', 'elixir'), ('KT', 'kotlin')], max_length=3, verbose_name='What technologies we use?'), blank=True, null=True, size=None),
        ),
    ]
