# Generated by Django 3.2.5 on 2021-08-26 11:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_organization_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='looking_for',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2, verbose_name='looking for those roles'), blank=True, choices=[('FE', 'Front-End Developer'), ('FS', 'Full-Stack Developer'), ('BE', 'Back-End Developer'), ('GD', 'Graphic Designer')], null=True, size=None),
        ),
    ]
