# Generated by Django 3.2.5 on 2021-08-03 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20210730_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='organization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.organization'),
        ),
    ]
