# Generated by Django 3.2.5 on 2021-08-24 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.IntegerField(choices=[(1, 'New Message'), (2, 'Join Request'), (3, 'Join Response'), (4, 'Deletion')])),
                ('message', models.CharField(max_length=255)),
                ('related_url', models.URLField(max_length=255, verbose_name='related url')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_to', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_from', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
