# Generated by Django 3.2.5 on 2021-08-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_receiver_notification_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'New Message'), (2, 'Join Announcement Request'), (3, 'Join Team Request'), (4, 'Join Response'), (5, 'Deletion')]),
        ),
    ]
